spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  datasource:
    hikari:
      maximum-pool-size: 90
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/devubitoms
    username: root
    password: ubimicro
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  kafka:
    consumer: 
      group-id: ms-user-consumer
logging:
  level:
    root: info
  config: logback-spring.xml
server:
  servlet:
    encoding:
      charset: UTF-8
  tomcat:
    uri-encoding: UTF-8
  port: 9071
